### ISSUE TITLE
Fix database class

### ISSUE THREAD

**Issue by carter-reynolds** [carter-reynolds/pyRPG_text#15]
Traceback (most recent call last):
  File "c:\Users\Carter\Documents\Github\pyRPG_text\main.py", line 42, in <module>
    main()
  File "c:\Users\Carter\Documents\Github\pyRPG_text\main.py", line 23, in main
    setup.create_db()
  File "c:\Users\Carter\Documents\Github\pyRPG_text\setup.py", line 33, in create_db
    db.create_game_tables()
  File "c:\Users\Carter\Documents\Github\pyRPG_text\classes\Database.py", line 18, in create_game_tables
    with open('/db/query/initial_table_setup.sql', 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/db/query/initial_table_setup.sql'

The game crashes if game.db doesn't exist. While the code properly generates this file, it requires a second launch to get into the game without crashing.

**Comment by carter-reynolds** [comment]
resolved
